import java.util.ArrayList;

public class Receipt {
    private int receiptId;
    private double totalCost;
    private int employeeId;
    private int tableNumber;
    private ArrayList<Integer> orderIds; // List of orders included in this receipt
    private String timestamp;
    private String paymentStatus; // "Paid", "Unpaid"

    // Constructor
    public Receipt(int receiptId, double totalCost, int employeeId, int tableNumber,
                  ArrayList<Integer> orderIds, String timestamp, String paymentStatus) {
        this.receiptId = receiptId;
        this.totalCost = totalCost;
        this.employeeId = employeeId;
        this.tableNumber = tableNumber;
        this.orderIds = orderIds;
        this.timestamp = timestamp;
        this.paymentStatus = paymentStatus;
    }

    // Getters and Setters
    public int getReceiptId() {
        return receiptId;
    }

    public void setReceiptId(int receiptId) {
        this.receiptId = receiptId;
    }

    public double getTotalCost() {
        return totalCost;
    }

    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }

    public int getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    public int getTableNumber() {
        return tableNumber;
    }

    public void setTableNumber(int tableNumber) {
        this.tableNumber = tableNumber;
    }

    public ArrayList<Integer> getOrderIds() {
        return orderIds;
    }

    public void setOrderIds(ArrayList<Integer> orderIds) {
        this.orderIds = orderIds;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    // Optional: Method to add an order ID to this receipt
    public void addOrderId(int orderId) {
        this.orderIds.add(orderId);
    }

    // Optional: Display receipt details
    public void displayReceipt() {
        System.out.println("=== RECEIPT ===");
        System.out.println("Receipt ID: " + receiptId);
        System.out.println("Table Number: " + tableNumber);
        System.out.println("Orders Included: " + orderIds);
        System.out.println("Total Cost: $" + totalCost);
        System.out.println("Payment Status: " + paymentStatus);
        System.out.println("Generated by Staff ID: " + employeeId);
        System.out.println("Time: " + timestamp);
        System.out.println("=================");
    }
}